name: Terraform Deployment
on:
  workflow_dispatch: # Manually triggered from GitHub UI
  push:
    branches:
      - main
env:
  PROJECT_ID: valid-micron-448222-n5
  COMPUTE_ZONE: us-east1-b
  TF_CONFIGURATION_DIR_PATH: ./tf-part-2

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ">= 363.0.0"
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10

      - name: Set GCP project and zone
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set compute/zone ${{ env.COMPUTE_ZONE }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{env.TF_CONFIGURATION_DIR_PATH}}

      - name: Import existing resources
        working-directory: ${{env.TF_CONFIGURATION_DIR_PATH}}
        run: |
          # Import the firewall resource
          terraform import google_compute_firewall.ssh projects/${{ env.PROJECT_ID }}/global/firewalls/vm-ssh || echo "Firewall resource already imported."

          # Import the network resource
          terraform import google_compute_network.default projects/${{ env.PROJECT_ID }}/global/networks/base-vpc || echo "Network resource already imported."

          # Import the storage bucket
          terraform import google_storage_bucket.remote-backend projects/${{ env.PROJECT_ID }}/buckets/remote-backend || echo "Storage bucket already imported."

          # Import the service account
          terraform import google_service_account.default projects/${{ env.PROJECT_ID }}/serviceAccounts/main-medium-vm-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com || echo "Service account already imported."

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: ${{env.TF_CONFIGURATION_DIR_PATH}}

      - name: Plan Terraform deployment
        run: terraform plan -out=tfplan
        working-directory: ${{env.TF_CONFIGURATION_DIR_PATH}}

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan
        working-directory: ${{env.TF_CONFIGURATION_DIR_PATH}}

      - name: Clean up Terraform artifacts
        run: rm -f tfplan
