region          = "us-east1"
subnetwork_name = "base-subnet"
vpc_name        = "base-vpc"
project_id      = "valid-micron-448222-n5"
subnet_cidr     = "10.0.0.0/24"
zone            = "us-east1-b"
vm_machine_type = "e2-standard-4"
